### ISSUE TITLE
shelljs error when building Android

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#237]
I'm seeing a missing `shelljs` error when I build Android using `cordova@4.0.0`.

```
$ cordova run android --device
Running command: /Users/mwbrooks/Development/lib/phonegap-app-developer/.cordova/hooks/before_prepare/compile-less.js /Users/mwbrooks/Development/lib/phonegap-app-developer
compiling LESS files

> phonegap-app-developer@ less /Users/mwbrooks/Development/lib/phonegap-app-developer
> lessc -x resources/less/app.less > www/css/app.css

Running command: /Users/mwbrooks/Development/lib/phonegap-app-developer/.cordova/hooks/before_prepare/test-runner.js /Users/mwbrooks/Development/lib/phonegap-app-developer
Running command: /Users/mwbrooks/Development/lib/phonegap-app-developer/.cordova/hooks/after_prepare/test-runner.js /Users/mwbrooks/Development/lib/phonegap-app-developer
Running command: /Users/mwbrooks/Development/lib/phonegap-app-developer/platforms/android/cordova/run --device

module.js:340
    throw err;
          ^
Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mwbrooks/Development/lib/phonegap-app-developer/platforms/android/cordova/lib/build.js:22:15)
```

**Comment by alexweber** [comment]
Just echoing Hirbod on this one, the workaround from his comment worked for me!
