### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by aunz** [phonegap/phonegap-app-developer#270]
I get this error when running phonegap serve
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)

the version is
phonegap --version
4.2.0-0.23.0
node --version
v0.10.35

**Comment by timkim** [comment]
Hi @aunz 

This issue is better located under the [connect-phonegap issues][https://github.com/phonegap/connect-phonegap/issues], but I'll help you out here. I have a feeling you might have some particular paths in your project which are the cause of that error. So you might want to check if you have any particular files that have special characters in them and try manually changing the file/folder name. That might be the cause. 

Otherwise, which OS are you running on?

**Comment by aunz** [comment]
Thanks! @timkim 
I am using Ubuntu 14.04. I created a brand name default hello world app and the problem still exists.

**Comment by gloaec** [comment]
Same here (cordova 4.2.0 / phonegap 4.2.0-0.24.1) on two different machines (ubuntu 12.04 & linuxmint) 
:( So frustrating ...

**Comment by timkim** [comment]
Hey there,
 
I finally got around to installing vagrant with a ubuntu distro on it (https://vagrantcloud.com/hashicorp/boxes/precise32 Ubuntu 12.04) only to find that it works on my end... 

Hrm, I'm not sure what is wrong at the moment, but here are some of my versions:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
```

```
phonegap -v 
4.2.0-0.24.2
```

```
node -v
v0.10.33
```

I'd be tempted to `console.log` right at `path.js:360:15` and see what is trying form the string. Might be able to see what is tripping the `path.join` function and go from there.

**Comment by fluffis** [comment]
I have the same error on windows.

Nodejs: 0.12.0
Phonegap: 4.2.0-0.23.0

```
TypeError: Arguments to path.join must be strings
    at f (path.js:200:13)
    at Object.filter (native)
    at Object.win32.join (path.js:205:38)
    at Object.handle (C:\Users\fabrahamsson\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\lib\middleware\cordova\cordova.js:21:33)
    at next (C:\Users\fabrahamsson\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\proto.js:193:15)
    at resume (C:\Users\fabrahamsson\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\middleware\static.js:65:7)

    at SendStream.error (C:\Users\fabrahamsson\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\middleware\stati
c.js:80:37)
    at SendStream.emit (events.js:107:17)
    at SendStream.error (C:\Users\fabrahamsson\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\node_modules\send\li
b\send.js:147:51)
    at SendStream.onStatError (C:\Users\fabrahamsson\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\node_modules\s
end\lib\send.js:248:48)
[phonegap] 500 /phonegap.js
```

**Comment by gloaec** [comment]
This is actually not a bug, I figured that this error occurs when you browse your application from a web-browser. Cordova's library will crash since it cannot load the plugins specific to the device environment. Still you can debug some part via the web-browser, but consider using [PhoneGap Developer App](http://phonegap.com/developer/) instead for device related features. Hope this helps.

**Comment by fluffis** [comment]
@gloaec, Yes, of cause that's the problem. Thanks alot!

**Comment by timkim** [comment]
Oh! 

Haha, I didn't realised people were using their regular web browsers to navigate to the address being served. Ya, that would probably do it.
