### ISSUE TITLE
PhoneGap Developer - App does not show latest changes

### ISSUE THREAD

**Issue by flyonthenet** [phonegap/phonegap-app-developer#287]
After last PhoneGap update, changes are not automatically transferred to Phonegap Developer App.
We have to close and restart the App to changes take effect.

This is very annoying :-(

Server platform (Phonegap serve): Windows Server 2003
Client: Adroid 5.1 (Nexus 5)

**Comment by timkim** [comment]
It takes a little bit for the new changes to update the app now (we changed some things internally). Give it a few more seconds to see if it updates. Over time we should be able to get the speed of the updates back to what they were.

**Comment by donovan-graham** [comment]
I'm having same issue on MacOSX + Samsung Galaxy S4.  Changes never propagate onto phone, so I'm having to manually restart after each change.

**Comment by Bushjumper** [comment]
+1

**Comment by flyonthenet** [comment]
@timkim After some tests, if I run `phonegap serve` with no arguments, the App never updates.
If I run `phonegap serve --autoreload` the App gets updates after a while (about 1 minute)
If I open `localhost:3000` in a standard browser, changes are immediate.

When loading, now seems that PhoneGap Developer downloads the entire app in a zip (takes more time to start)

There's some way to restore the previous behavior? It was so handy! :-)
Thanks in advance

**Comment by timkim** [comment]
Hrm - well it looks like we have some kinks to work out. Ya, we changed the `PhoneGap Developer App` to download the entire app as a zip - it fixed issues concerning AJAX, certain api calls and such, but it seems like performance took a hit. 

To restore the previous behaviour would require a downgrade of the app to `1.4.0`.

**Comment by itwseood** [comment]
@timkim we have performed some tests with the following configurations:
- win 8, PhoneGap Cli (5.0.0-0.28.0) and iPad Mini, iPhone 6, Samsung Galaxy S3 - all of these with the latest release of PG Developer App.
- Yosemite os, PhoneGap Cli (5.0.0-0.28.0) and iPad Mini, iPhone 6, Samsung Galaxy S3 - all of these with the latest release of PG Developer App.

I am sending some insights, hope those will help:
- An app update after a file save usually takes ~30s with the download. 
- Very common scenario is the download to fail, when a file is updated. http://screencast.com/t/Q35v1eJ0g47J - This is solved when we terminate the app server, close the developer app and then restart the app server and the dev app. Then in few saves we often end up to the same case.
- Often the app gives Alert that is "Unable to download the archive from the server. Please upgrade the PhoneGap Cli or check your network settings". Since we did not change anything in our dev network environment after the latest update and the CLI is up to date, I guess the reason for download fail is not related to both of the reasons. 
- On some point I've got this error that might be useful, although it might not be directly related (win 8 environment)l:
```
fs.js:568
  function strWrapper(err, written) {
                ^
Error: EMFILE, too many open files 'C:\Users\XXX\AppData\Roaming\npm\node_mod
ules\phonegap\node_modules\connect-phonegap\res\middleware\deploy.js'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at injectScript (C:\Users\XXX\AppData\Roaming\npm\node_modules\phonegap\n
ode_modules\connect-phonegap\lib\middleware\zip.js:40:34)
    at InjectHTML._transform (C:\Users\XXX\AppData\Roaming\npm\node_modules\p
honegap\node_modules\connect-phonegap\lib\middleware\zip.js:62:68)
    at InjectHTML.Transform._read (_stream_transform.js:179:10)
    at InjectHTML.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at InjectHTML.Writable.write (_stream_writable.js:217:11)
```
Hope this helps! Let me know if we can help performing some additional tests if needed. Our team likes PhoneGap (and Cordova) we have active projects using it and indeed the Developer App saves huge amount of time. I'm sure these glitches with the the DevApp update will be solved and this toll will continue to be as fast and smooth as before and better in form of possibilities.

You've mentioned downgrade to 1.4.0 - is the previous version available somewhere to get as PG Dev App?

**Comment by itwseood** [comment]
Additional insight that might be helpful. Noticed that if using MAC and the app is open in BOTH the browser (localhost:3000) and via the iOS Phonegap Developer app, the extraction of the app never crashes and reloads the app preview appropriately.

**Comment by Bushjumper** [comment]
@timkim Any progress on this? If not, could you please provide a way to downgrade? Thanks

**Comment by rodrigozr** [comment]
+1
Also, I would like to add that "console.log" output also stopped working in the latest version. Do anybody have a link to the old APK?

**Comment by mwbrooks** [comment]
Hey @flyonthenet @donovan-graham @itwseood, thanks a lot for all of the details! Seriously, it's hard to recreate various environments using various devices, so this kind of testing and reporting helps a lot.

I've noticed that #292 is also having issues on an iPhone 5. Referencing it here so that the Github issues link to each other.

We'll need to dive into this issue more seriously, since it's not a trivial fix. I totally understand if you need to downgrade in order to get back into dev-mode. We archive all of our releases inside of the repository and you can find the [Android releases here](https://github.com/phonegap/phonegap-app-developer/tree/master/resources/release/android). You should be able to install the Android releases as long as third-party apps are enabled on the device. iOS obviously isn't as simple.

**Comment by flyonthenet** [comment]
Hi @mwbrooks @timkim

This is what I can report after some days of developing with the new PhoneGap.

1) *Seems some files are cached*. The App gets auto-reloaded fine (i see HTML changes) but scripts (frequently) are old. So, when my App is not working as I expect, I don't know if it's a fault in my code or a cache related problem. I usually place a huge `alert` in JS code, and if not shown, I insist on reaload.

2) *When I save JS or CSS, changes are not propagated* to the App. I have to save some HTML related file to get my App updated. Sometimes this is not sufficient, so I have to close and reopen PhoneGap. May this can be related to same cache issue?

Do you think that `<meta http-equiv="pragma" content="no-cache" />` will help to mitigate this?
Or how I can tell PhoneGap to turn off any caching?

@rodrigozr Actually I'm using `console.log` with no problems. Have you tried to run `phonegap serve --autoreload`?

Have a nice day
D.

**Comment by sarvansri** [comment]
Hi, 
i am new in phonegap, i am developing a simple app in cordova.

I have auto reload issue in phonegap developer app. If i change files in project folder, its not updated in developer app, i don't have a line "200  /autoreload" in cmd windows.

**Comment by jdillon11** [comment]
I noticed this problem a few weeks ago when I updated to the newest version of PhoneGap, so I waited a few weeks, uninstalled PhoneGap, created a new project, updated the developer app on my phone, and everything still seems broken. This is really disappointing and frustrating as I can't really get the work done I need to. Is there a timeframe on when this will be fixed, or any other updates on the problem?

Thanks,
Josh

**Comment by mwbrooks** [comment]
Hey @jdillon11,

Yea, this is a frustrating issue. We've got a patch waiting in the Apple submission queue and we'll release it once it's approved. The patch helps address some reload issues, where the previous content was cached. We're now trying to diagnose the connection (or _download error_) message that users are seeing.

**Comment by timkim** [comment]
Hi all,

Our update to fix the autoreload issue should now be up. Please update your app and see if the autoreload feature works for you.

**Comment by lucifertran** [comment]
Hi,

I still face problem with HTML not reload. I tried to fixed one issue by modifying the html, turn out it did not work out. So I switch back to the old one, and Phonegap app did not update at all. 

Anyone facing the same problem?

**Comment by vrathnam7** [comment]
I am also still facing this issue from both the CLI and the desktop application from my Mac. The three finger tap and four finger tap also do not work. I am using the most recent version of phonegap. Any updates on this?

**Comment by TanaseButcaru** [comment]
Same issue here! Using CLI on Linux with latest phonegap / cordova / nodejs versions.
Tested on a Xperia Z3c.

**Comment by owenconti** [comment]
Having the same symptoms as @vrathnam7 - No automatic refresh, no 3/4 tap gestures working. Only way to reload the app is to force quit the Phonegap Developer App and reopen it. I have the most recent version of the Phonegap CLI and Phonegap Developer App as of today (Aug 15, 2015)

**Comment by Xyclade** [comment]
Same here using Mac OS Yosemite,  the IOS and Android app (latest versions)

**Comment by MilosRasic** [comment]
Hi. I have a similar problem, except that it occurs one one machine only (work) and the app is working fine on another (home). Both computers are running Windows. The client is Android. Any news or workarounds for this problem?

**Comment by seltzlab** [comment]
Same here with Ubuntu + CLI, Phonegap 5.2.1 and latest Android app

**Comment by indice** [comment]
+1

**Comment by imovertheinternet** [comment]
+1

**Comment by gecsafunk** [comment]
+1

**Comment by francescognarra** [comment]
+1

**Comment by crushcafeteria** [comment]
+1

**Comment by diogomachado** [comment]
+1. I try with Moto X, Android Lollipop. When i change, the Phonegap App not autoreload.

**Comment by luco** [comment]
+1

**Comment by yorkshiretwist** [comment]
I have a dirty workaround for seeing changes with CSS and JS files when using PhoneGap Desktop. Rather than link to the local file:

`<link rel="stylesheet" type="text/css" href="css/index.css" />`

Link to the one on the PhoneGap server:

`<link rel="stylesheet" type="text/css" href="http://192.168.1.100:3000/css/index.css" />`

You'll need to change the IP address and port with the one your server uses. This means you can refresh the app on your device (using four-finger tap) to load changes.

Before preparing your app for deployment you'll need to change the URLs back to the local ones.

**Comment by crosma** [comment]
+1 fresh install of the desktop and phone apps. Worked for about an hour of testing a brand new app. It still works perfect if I go to http://localhost:3000/ locally.

**Comment by nakanaa** [comment]
I had this problem (hence ending up in here), but I thought it was weird because it had been working just a couple days before.

For me it was simply an exception in one of the JavaScript files. Turns out, that exception somehow stopped the whole app from updating (even if it wasn't critical to the app itself and the server did notice the changes etc.). The exception was actually plugin related for me.

Anyway, if you're having the problem at least make sure there isn't any exceptions being produced by your code, try disabling/removing (custom) plugins and generally commenting out your app to very bare minimum to see if it starts working. If it does, then you know it's related to your code.

**Comment by BrainSlugs83** [comment]
+1 -- I started out with latest phonegap, and it was working at first, but as my project got larger, it stopped working (I haven't even added all the NPM modules I want to add yet) -- downgrading to 1.4 seems to have fixed this -- on 1.4, within a couple of seconds of saving my changes, they show up on the phone.

**Comment by MusicDemon** [comment]
I've noticed the same issue after some hours of testing. I'm unsure if this has to do with any caching of the DevApp side. But I also noticed this error;

```
undefined exeption nativeEvalAndFetch : ReferenceError: Can't find variable: cordova
undefined exeption nativeEvalAndFetch : ReferenceError: Can't find variable: cordova
```

The rest of the DevApp log says near to nothing when something happens, sadly.

**Comment by lesliepound** [comment]
Is the solution to downgrade to 1.4?  
Same problem of app not refreshing in phonegap test  tool (installed on windows,using iphone5);

**Comment by enriquerene** [comment]
Can someone tell me why "phonegap serve" doesn't work on linux but works on windows? The command works ok, and I can connect with my firefox browser. When I try to connect in my mobile through PhoneGap developer app, it keeps downloading and after cancel because of don't find anything... when I do the same in a windows 7 after few seconds the app says "extracting" and everything works fine. I tried in Ubuntu 15.04, 15.10, 14.04 LTS and now I'm in OpenSUSE Tumbleweed.

Thank you

**Comment by fultonm** [comment]
This is still an issue.. With phonegap serve --autoreload I still receive no updates to the app after 10 minutes. The CLI does register file changes.
https://i.gyazo.com/ac669283b3e4882e686df1b9133891db.png

**Comment by ibrennan** [comment]
Facing the same problem still, running phonegap version 5.4.0 from command line:

phonegap serve

It live reloads in the browser the problem, but using the on device phonegap app we get no refreshes.

ETA for a fix?

**Comment by enriquerene** [comment]
I know this doesn't solve the issue, but I'm testing my apps through
'cordova run android' and plugging my device
Am 13.01.2016 19:26 schrieb "Ian Brennan" <notifications@github.com>:

**Comment by arslion** [comment]
+1. same issue happening with me right now :/

**Comment by gRegorLove** [comment]
I was experiencing this until I (temporarily) removed the Content-Security-Policy meta tag.

**Comment by Tuszy42** [comment]
I can confirm what @gRegorLove said, deleting that line in the index solves the issue.

**Comment by lesliepound** [comment]
Still getting error after "Content-Security-Policy" removed and  file edited. Console log shows: "download error"

**Comment by samanime** [comment]
So, I noticed a change when I removed the Content-Security-Policy meta tag and that seemed to fix it, but I've been testing for a while again, with it gone all this time, and it's now slow again.

It's not that it doesn't work at all... it's just really slow. Like, on the order of a couple of minutes. Sending deviceready is also the same... taking several minutes to trigger.

It seems like if I do several changes in rapid-fire, it'll get way behind as it tries to do each change.

Running it in the browser, it works at expected speeds (a few seconds at most).

The CLI sees the changes pretty much instantly.

**Comment by rahul-desai3** [comment]
+1

**Comment by rodrigoclp** [comment]
+1
Sometimes work, sometimes not.

**Comment by phuongtailtranminh** [comment]
+1
Sometimes work, sometimes not.

**Comment by bodazhao** [comment]
Is there a solution to this problem? My course at uni got this assignment using phonegap, and because the mobile app on the tablet won't refresh itself and the 4 finger tap refresh won't work either, i had to manually go back to the menu and connect again everytime i want see a change! This is really troublesome, and i'm less likely to come back to phonegap afterward when I finish with this assignment.

**Comment by rahul-desai3** [comment]
I don't mean to sound like a jerk but the Intel XDK works a lot better. Just saying.
I have moved on.

**Comment by omarwagih** [comment]
+1

**Comment by khoaofgod** [comment]
I am not the only one.. Hahah, so, Intel XDK from now.

**Comment by jensbits** [comment]
Seems that PG Developer is assuming you have a single page app as auto reload only works for me if I'm on the index.html page or go back to it after making a change. If I'm on register.html in PG Developer and make a change, it shows file changed but will not reload the change until I go to the index.html page of the app. Unfortunately, I have to log out of my app to go back to the index page and then log in again to see the change.

Why doesn't PG Developer auto reload on pages other than index.html?

**Comment by timkim** [comment]
Hi @jensbits 

Yes, autoreload should work on other pages other than index.html. Did you include a script reference to cordova/phonegap on your other pages?

**Comment by jensbits** [comment]
@timkim Yes, I do. So I checked if there was a difference in the code where cordova was referenced and I found this:

On the index.html I had:

`<script type="text/javascript" src="cordova.js"></script>`

And, on the other pages, I had this:

`<script src="cordova.js"></script>`

After adding `type="text/javascript"` everything started auto-reloading again on the other pages.

Thanks for making me look a lit harder.

**Comment by moneer99** [comment]
This problem happened with me but when I excyted the build command with --verbose,  the problem was just wrong permissions. So, make sure that the current user that run the command has the permissions to write into the app directory.

**Comment by illiniguy** [comment]
+1

Pretty sure this broke again in a recent build. Cannot auto refresh or use any tap gestures whatsoever. iOS and Android. Testing with default apps created with the desktop app.

**Comment by jksoegaard** [comment]
Also broken here when using the current 0.3.4 build from phonegap.com. I have installed on a fresh Mac and iPhone (haven't had Phonegap Desktop/Developer on them before) - and they do not auto refresh the content. Viewing the site in Google Chrome on the desktop auto refreshes properly.

**Comment by renalpha** [comment]
Same here, IOS. Installed it 5 minutes ago.

**Comment by surajpindoria** [comment]
Hi @illiniguy, @jksoegaard, @renalpha,

Version 0.3.4 of the desktop app has a bug related to the updated `connect-phonegap` module that is causing these problems in the developer app. We already have a fix and will release version 0.3.5 soon. In the meantime, using the CLI and running `phonegap serve` will work properly.

**Comment by surajpindoria** [comment]
Version 0.3.5 of the desktop app has been released

**Comment by rxtcreagh** [comment]
Installed 0.3.5 an hour ago and for some reason it doesn't see my changes. Do I need to do something else to get my changes to appear? Running the PhoneGap desktop app and using iPhone 6.

**Comment by jksoegaard** [comment]
Works for me now with 0.3.5!

**Comment by rxtcreagh** [comment]
I have had some luck but mostly I have to close the browser or iPhone app, quit PhoneGap and restart for any changes I make. I've tried stopping the app and starting it but so far that hasn't seemed to help. jksoegaard are you seeing the changes work as you save them and are you running the browser or the app? Thank you, tim

**Comment by jksoegaard** [comment]
Yes, the display updates as I save the HTML/JS files. It works for me both with the browser and the app.

If you have to restart the PhoneGap Desktop program, you're having a different problem than the one I was having. I had to restart the app.

**Comment by rxtcreagh** [comment]
If I make any change, say add a <div> I get this message 

Error:Not found

I then have to close everything, restart phonegap and relaunch the browser or app. So I end up having to quit and relaunch about 40-60 times a day making it difficult to test things. I must have a setting wrong it sounds like you don't have the problem.

-tim-

**Comment by hellboywar** [comment]
I have phonegap-cli 6.3.0 installed and autoreload on device works only if cordova.js added in html exatly that way:

`<script type="text/javascript" src="cordova.js"></script>`

Any other way is broken

**Comment by asteriskman7** [comment]
I had this problem from a web browser after I accidentally ran `phonegap serve` as root. That resulted in files in the platforms directory being unwritable by a non-root user. Removal of everything in platforms as root resolved the issue and the web browser now sees updates correctly.

**Comment by keymarkstuart** [comment]
@hellboywar is right for me.  EXACTLY LIKE THIS in the index.html works other suggestions do not

<script type="text/javascript" src="cordova.js"></script>

**Comment by kalliste** [comment]
+1

**Comment by Radivarig** [comment]
Reloading to work in my case:

1. `cordova.js` script has to be **without attributes** like @hellboywar said, (at least without `charset="utf-8"`)
2. `cordova.js` script has to be **last**. Otherwise a script after it `bundle.js` (`webpack`) was not even loaded.

My working [template repo](https://github.com/Radivarig/rad-react-template)

**Comment by Papipo** [comment]
Also, I was wondering if not downloading a ZIP would allow webpack-dev-server to be used directly as a development setup.

**Comment by 3Darklight** [comment]
lol, having to write
`<script type="text/javascript" src="cordova.js"></script>`
was actually it.
I don't include the type anymore, since it's the default in the HTML5 spec anyway:
https://www.w3.org/TR/html5/scripting-1.html#attr-script-type

So can this please be fixed in one of the next releases? Writing
`<script src="cordova.js"></script>`
shouldn't break anything.

**Comment by flyonthenet** [comment]
For me, things are running pretty good with latest version of CLI and PhoneGap Developer.
The apps are realoding almost always.
I suggest to close this (old) bug.

**Comment by IceReaper** [comment]
I've got the same problem here. When i use google chrome, stuff works correctly: auto-reload on change + ajax and console.log working. However on android using the developer app, i no not get any console.log shown, plus fetching some json via ajax doesnt work plus the reloading does not work too. I however get a "Content Security Policy" warning on the device, which i do not get on the browser. Related?

**Comment by Hissvard** [comment]
It's old but it does keep coming back from time to time, I got here via Google because I was having the same issue a few minutes ago :/

My solution was simply moving the folder.
I'd accidentally cloned the repo inside `Program Files` and it wasn't working - moving it back to the Desktop actually got everything running again.
Which leads me to think @m0uneer's hunch about permissions is one of the most likely causes.

**Comment by ivangarcia88** [comment]
+1

**Comment by Yatima1460** [comment]
I have the same problem and the simplest solution is to just remove and re-add the platform you are working with.

**Comment by Shivang44** [comment]
@hellboywar Your solution worked for me. Including it like this:

`<script type="text/javascript" src="cordova.js"></script>`

Is required. This is a little annoying because I wanted to require cordova.js as a module with requirejs, but this works for now. If anybody has found a workaround for this with requirejs please let me know!

**Comment by mmtechslv** [comment]
Editing index.html with Kate does update the App but if you use Gedit such problem does not exists.

**Comment by conradkirschner** [comment]
as nobody said that before .... 

you should:  Including it like this:

<script type="text/javascript" src="cordova.js"></script>
