### ISSUE TITLE
Can't build or run phonegap-app-developer

### ISSUE THREAD

**Issue by omefire** [phonegap/phonegap-app-developer#304]
I've been trying to build and run the phonegap-app-developer on my Ubuntu box. 
I'm able to create a new phonegap app and have it running on a device/emulator, 

However, I keep getting the following error when I try running/building the phonegap-app-developer itself : 

"
BUILD FAILED
/home/omefire/android-sdk-linux/tools/ant/build.xml:597: The following error occurred while executing this line:
/home/omefire/android-sdk-linux/tools/ant/build.xml:649: The following error occurred while executing this line:
/home/omefire/android-sdk-linux/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/home/omefire/Cordova/phonegap-app-developer/platforms/android/CordovaLib/${aapt}" (in directory "/home/omefire/Cordova/phonegap-app-developer/platforms/android/CordovaLib"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617) ... "

**Comment by omefire** [comment]
running 'cordova run android' works out fine. that's what I ended up using.

**Comment by omefire** [comment]
This issue is due to android sdk tools version 24.3.2 being broken : https://code.google.com/p/android/issues/detail?id=176488
