### ISSUE TITLE
Connection Issue - Feedback

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#307]
To better understand where each developer's connection issue is occurring, we'd appreciate you taking the time to fill out this survey!

## 1. What operating system are you using?

If you are using Windows, please let us know if it’s 32-bit or 64-bit?

For example:

- OS X
- Windows 7 32-bit
- Windows 8.1 64-bit

## 2. Do you have a software firewall enabled?

By default, Windows often has the built-in firewall enabled. You can check under your system settings.

## 4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?

For the PhoneGap CLI, you can check your version by typing `phonegap --version`

For the PhoneGap Desktop, you can check your version by selection `? -> About` on the sidebar.

## 5. What mobile device platform are you using?

Is it Android, iOS, or Windows Phone?

We would appreciate knowing the version as well. For example, iOS 8.3 or Android 5.1.

## 6. In the past, have you successfully paired the CLI/Desktop to the mobile app?

Has your network changed since the last successful connection?

## 7. Can you download the app archive locally?

1. Open and serve a project
  - On the PhoneGap Desktop, open a project and ensure the bottom banner is green and lists an IP address.
  - On the PhoneGap CLI, navigate into a project and run `phonegap serve`

1. Open your desktop web browser
  - Please ensure that the browser is Safari or Chrome.
  - Browse to `x.x.x.x:3000/__api__/appzip`
  - Substitute `x.x.x.x` for your IP address, such as `10.0.1.7:3000/__api__/appzip`
  - If this step fails, please try `localhost` and let us know if that works instead.

1. A zip archive should be downloaded

1. Unzip the archive and ensure that your project files exist.
  - The files exist or don’t, so there is no need to inspect each file.

1. Do you see any `404` or `error` messages in the PhoneGap CLI output or PhoneGap Desktop log file?
  - You can access the PhoneGap Desktop log from the sidebar window icon.

## 8. Can you download the app archive on your mobile device browser?

Now we are going to do the same steps as above, but on your mobile device browser. This will tell us whether the network connection is okay.

1. Open and serve a project
  - On the PhoneGap Desktop, open a project and ensure the bottom banner is green and lists an IP address.
  - On the PhoneGap CLI, navigate into a project and run `phonegap serve`

1. Open your mobile web browser
  - Please ensure that the browser is Mobile Safari, Mobile Chrome, Android Browser, or IE.
  - Browse to `x.x.x.x:3000/__api__/appzip`
  - Substitute `x.x.x.x` for your IP address, such as `10.0.1.7:3000/__api__/appzip`

1. A zip archive should be downloaded

1. Do you see any `404` or `error` messages in the PhoneGap CLI output or PhoneGap Desktop log file?
  - You can access the PhoneGap Desktop log from the sidebar window icon.

## 9. Can you download the app archive with the PhoneGap mobile app?

Next, we are going to repeat the same step as above but use the PhoneGap mobile app. This will tell us if the connection problem is due to the app rather than the desktop client.

1. Open and serve a project
  - On the PhoneGap Desktop, open a project and ensure the bottom banner is green and lists an IP address.
  - On the PhoneGap CLI, navigate into a project and run `phonegap serve`

1. Open your PhoneGap Developer App
  - Connect to `x.x.x.x:3000`
  - Substitute `x.x.x.x:3000` for your IP address, such as `10.0.1.7:3000`

1. You should see a `Connecting…` and `Extracting…` message followed by your app.

1. Do you see any `404` or `error` messages in the PhoneGap CLI output or PhoneGap Desktop log file?
  - You can access the PhoneGap Desktop log from the sidebar window icon.

## 10. Tell us a little more about your app

1. How large is the `www/` directory?
1. How many files are in the `www/` directory?

## 11. Does a Hello World App work?

Finally, we would like to rule out your app has the problem by testing the default Hello World app.

1. Create a new app and begin serving it
  - On the PhoneGap Desktop, create a project and ensure the bottom banner is green and lists an IP address.
  - On the PhoneGap CLI, create a project using `phonegap create my-new-app`, change into the project, and run `phonegap serve`

1. Open your PhoneGap Developer App
  - Connect to `x.x.x.x:3000`
  - Substitute `x.x.x.x:3000` for your IP address, such as `10.0.1.7:3000`

1. You should see a `Connecting…` and `Extracting…` message followed by your app.
  - If the above fails, please try connecting using your mobile web browser.
  - If it continues to fail, please try connecting using your desktop web browser.

**Comment by cblgh** [comment]
### 1. What operating system are you using?
Windows 7 64-bit
### 2. Do you have a software firewall enabled?
Yes.
### 3. Are you using the PhoneGap CLI or PhoneGap Desktop?
PhoneGap CLI
### 4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?
PhoneGap CLI version 5.0.0-0.28.1
### 5. What mobile device platform are you using?
iOS 7.1.2
(Running the older version of the PhoneGap Developer App on an Android mobile, however, works without any issues. This is however not true if the app is updated.)
### 6. In the past, have you successfully paired the CLI/Desktop to the mobile app?
Yes, and I think the network is the same, although I don't know for sure.
### 7. Can you download the app archive locally?
Yes, although no zip archive is downloaded - all I see is our splash screen for the app.
(The browser used was Firefox 38.0.5)
This error also appears in the log:
```
[phonegap] 200 /
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Object.handle (C:\Users\Alex\AppData\Roaming\npm\node_modules\phonegap\no
de_modules\connect-phonegap\lib\middleware\cordova\cordova.js:21:33)
    at next (C:\Users\Alex\AppData\Roaming\npm\node_modules\phonegap\node_module
s\connect-phonegap\node_modules\connect\lib\proto.js:193:15)
    at resume (C:\Users\Alex\AppData\Roaming\npm\node_modules\phonegap\node_modu
les\connect-phonegap\node_modules\connect\lib\middleware\static.js:65:7)
    at SendStream.error (C:\Users\Alex\AppData\Roaming\npm\node_modules\phonegap
\node_modules\connect-phonegap\node_modules\connect\lib\middleware\static.js:80:
37)
    at SendStream.EventEmitter.emit (events.js:95:17)
    at SendStream.error (C:\Users\Alex\AppData\Roaming\npm\node_modules\phonegap
\node_modules\connect-phonegap\node_modules\connect\node_modules\send\lib\send.j
s:147:51)
    at SendStream.onStatError (C:\Users\Alex\AppData\Roaming\npm\node_modules\ph
onegap\node_modules\connect-phonegap\node_modules\connect\node_modules\send\lib\
send.js:248:48)
[phonegap] 200 /css/style.css
[phonegap] 200 /js/vendor/fastclick.js
[phonegap] 200 /js/rss.js
... other 200s omitted for brevity
[phonegap] 200 /socket.io/?EIO=2&transport=polling&t=1434586737556-2&sid=Q48u
UEHx2Y_qtAAAB
[phonegap] 200 /__api__/autoreload
```
### 8. Can you download the app archive on your mobile device browser?
I see the same splash screen as in step 7, although there is no error in the log.
(I used the safari browser that is distributed with iOS 7)
### 9. Can you download the app archive with the PhoneGap mobile app?
No, all I see is the "Downloading..." message in the Developer App and the CLI crashes, as per #299.
### 10. Tell us a little more about your app
`www/` is 4.15 MB and contains 154 files distributed over 47 folders
### 11. Does a Hello World App work?
No.

**Comment by millenniumgdjordan** [comment]
1. What operating system are you using?
OSX 10.10.3

2. Do you have a software firewall enabled?
No.

3. Are you using the PhoneGap CLI or PhoneGap Desktop?
PhoneGap CLI

4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?
5.0.0-0.28.1

5. What mobile device platform are you using?
iOS 8.3

6. In the past, have you successfully paired the CLI/Desktop to the mobile app?
Yes

7. Can you download the app archive locally?
sometimes I can.  it seems if i use localhost:3000/__api__/appzip I have better luck than the actual ip address. but sometimes I download using ip address no problem. not sure what the conditions are. It seems the same to me.

Do you see any 404 or error messages in the PhoneGap CLI output or PhoneGap Desktop log file?

One of two:

1.) Error: ENFILE, file table overflow '/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/res/middleware/deploy.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at injectScript (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:40:34)
    at InjectHTML._transform (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:62:68)
    at InjectHTML.Transform._read (_stream_transform.js:179:10)
    at InjectHTML.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at InjectHTML.Writable.write (_stream_writable.js:217:11)


2.) events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENFILE, open '/Users/webdev/Sandbox/millenniumbookviewer/www/node_modules/grunt-autoprefixer/node_modules/chalk/node_modules/ansi-styles/index.js'
    at Error (native)


8. Can you download the app archive on your mobile device browser?

no

Do you see any 404 or error messages in the PhoneGap CLI output or PhoneGap Desktop log file?
404 error in console for /__api__/appzip

9. Can you download the app archive with the PhoneGap mobile app?
I get DOWNLOADING... there is a long period then an alert
"Unable to download archive from the server" "Unable to properly connect to the server"

10. Tell us a little more about your app

How large is the www/ directory?
431.4MB
How many files are in the www/ directory?
3612
11. Does a Hello World App work?
yes

**Comment by niels515** [comment]
**1. What operating system are you using?**
Windows 8.1 Pro 64-bit
**2. Do you have a software firewall enabled?**
NO
**3. Are you using the PhoneGap CLI or PhoneGap Desktop?**
Desktop
**4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?**
0.1.7
**5. What mobile device platform are you using?**
Android 5.0.2
**6. In the past, have you successfully paired the CLI/Desktop to the mobile app?**
Succesfully paired in the past
No network change
**7. Can you download the app archive locally?**
Yes and no, I can download it but it can't open: the zip file is invalid
**8. Can you download the app archive on your mobile device browser?**
Nope, download fails every time
**9. Can you download the app archive with the PhoneGap mobile app?**
No,
Alert
Unable to download archive from the server
Unable to properly connect to the server
**10. Tell us a little more about your app**
1.24MB, 50 files and 5 folders
**11. Does a Hello World App work?**
Bluestacks (android simulator for desktop) : YES
Android phone: NO

**Comment by FireCoding** [comment]
I see that it's been a while, but for what it's worth... in my case connection issues show up on Android 4.1 device only.


**1. What operating system are you using?**
Windows 7 64-bit

**2. Do you have a software firewall enabled?**
No

**3. Are you using the PhoneGap CLI or PhoneGap Desktop?**
both CLI AND desktop exhibit same behavior/logs

**4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?**
CLI - 5.1.1
Desktop - 0.1.8

**5. What mobile device platform are you using?**
Android 4.1.1    **<<< THIS SEEMS TO BE THE PROBLEM**

**6. In the past, have you successfully paired the CLI/Desktop to the mobile app?**
It works even now but it's SLOOOOOOOOOOOOOOOOW.  Takes 45 seconds for a simple hello world page update.

**7. Can you download the app archive locally?**
Downloads fine in the browser every time.  The zip file unzips just fine.  No problems here.

**8. Can you download the app archive on your mobile device browser?**
Downloads fine here too.  No problems here.

**9. Can you download the app archive on your mobile device browser?**
This works fine - initial load is a success.  However, it is VERY SLOOOOWWWW.

**10. Tell us a little more about your app**
Hello world app - default "phonegap create helloword" skeleton.  I'm just modifying index.html and I have to wait 45-60 seconds for an update.

**11. Does a Hello World App work?**
Like I said, it does work but it is toooooo slooooooooow.

**More info:**
iPhone 4s running iOS 8.4 **works fast**
phone running Android 5.1 **works fast**

It seems to be the Android 4.1 OS.  Is this not a supported version for this tool?  If not, Google Play should have stopped me with "not compatible with your device", no?

BTW, LOVE this tool

**Comment by Pckmule** [comment]
1. What operating system are you using?

Windows 8.1 64-bit

2. Do you have a software firewall enabled?

Windows Firewall

3. Are you using the PhoneGap CLI or PhoneGap Desktop?

PhoneGap Desktop

4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?

0.1.8

5. What mobile device platform are you using?

Android 4.4.2

6. In the past, have you successfully paired the CLI/Desktop to the mobile app?
No, first time trying to do this.

7. Can you download the app archive locally?

I can download from http://localhost:3000/__api__/appzip (using Chrome). 
The appzip file appears to contain the www folder with all the expected files.

Attempting to download from the server provided does not work. No errors are returned, but the request just continues until it times out. 

8. Can you download the app archive on your mobile device browser?

No, attempting to download from the server provided does not work on my mobile phone either. Same problem as from my PC - no errors are returned, but the request just continues until it times out. 

9. Can you download the app archive with the PhoneGap mobile app?

No, appears to fail due to timeout.

10. Tell us a little more about your app

This is the default template provided when you create a new project using the PhoneGap Desktop App. The www folder is ~1.4mb in size.

11. Does a Hello World App work?

No

**Comment by archanalive** [comment]
Hello, I am facing a similar issue with PhoneGap desktop app.http://<myip>:3000/api/appzip gives  '404 /__api__/appzip in the PhoneGap server logs. Also i see 'Cannot Get /api/appzip on the local browser.
I have tried giving permissions to the project i created.
Is there something i am missing on configuration side?

**Comment by nicszerman** [comment]
Was filling the survey when It read about the firewall and a light bulb appeared over me, turned it off and magically the app was working. 
You should add somewhere an alert like "Remember to turn off your firewall", I had completely forgotten.

**Comment by ctinach** [comment]
I have a similar issue  on Windows x64. I updated npm, disabled the firewall, etc... but I still get a 500 server error for cordova.js. If I try to access it directly this is what I get 
```
TypeError: Arguments to path.join must be strings at f (path.js:178:13) at Object.filter (native) at Object.win32.join (path.js:183:38) at Object.handle (D:\TMP\nw3448_11965\node_modules\connect-phonegap\lib\middleware\cordova\cordova.js:21:33) at next (D:\TMP\nw3448_11965\node_modules\connect-phonegap\node_modules\connect\lib\proto.js:193:15) at resume (D:\TMP\nw3448_11965\node_modules\connect-phonegap\node_modules\connect\lib\middleware\static.js:65:7) at SendStream.error (D:\TMP\nw3448_11965\node_modules\connect-phonegap\node_modules\connect\lib\middleware\static.js:80:37) at emitOne (events.js:75:13) at SendStream.emit (events.js:150:7) at SendStream.error (D:\TMP\nw3448_11965\node_modules\connect-phonegap\node_modules\connect\node_modules\send\lib\send.js:147:51)

```

is there any workaround to this?

**Comment by ApocalypsjeNL** [comment]
1. What operating system are you using?
Windows 8.1  64-bit
2. Do you have a software firewall enabled?
Yes
3. Are you using the PhoneGap CLI or PhoneGap Desktop?
Desktop
4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?
0.1.10
5. What mobile device platform are you using?
Android 4.2.2
6. In the past, have you successfully paired the CLI/Desktop to the mobile app?
No
7. Can you download the app archive locally?
Yes
8. Can you download the app archive on your mobile device browser?
No
9. Can you download the app archive with the PhoneGap mobile app?
No,
Unable to download archive from the server
Unable to properly connect to the server
10. Tell us a little more about your app
76,0 kB, 6 files and 3 folders
11. Does a Hello World App work?
No

**Comment by vbelinschi** [comment]
1. What operating system are you using?
    Windows 8.1 64-bit

2. Do you have a software firewall enabled?
    Windows Firewall, tried disabling it, to no avail

3. Are you using the PhoneGap CLI or PhoneGap Desktop?
    PhoneGap CLI
4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?
    PhoneGap CLI 5.3.6

5. What mobile device platform are you using?
   Windows Phone 8.1
   Android 4.4.2

6. In the past, have you successfully paired the CLI/Desktop to the mobile app?
   No
7. Can you download the app archive locally?
   Yes

8. Can you download the app archive on your mobile device browser? 
   No
9. Can you download the app archive with the PhoneGap mobile app?
   No
10. Tell us a little more about your app
   1.42 MB
   56 files

11. Does a Hello World App work?
   No

**Comment by bonododo** [comment]
What operating system are you using?
Windows 7 64-bit

Do you have a software firewall enabled?
Windows Firewall disabled
Avast disabled  (Was working on the 13/10 before with avast and firewall running)

Are you using the PhoneGap CLI or PhoneGap Desktop?
PhoneGap Desktop

What version of the PhoneGap CLI or PhoneGap Desktop are you using?
PhoneGap Desktop 0.1.11
Phonegap developer 1.5.6

What mobile device platform are you using?
Android 5.0 (phone)
Android 5.1.1 (tablet)

In the past, have you successfully paired the CLI/Desktop to the mobile app?
Yes. Here is a list of changes 9 i might forget something) since it worked:
*install, remov virtualbox.  deactivate all network except wifi
*upgrade of cisco any connect 
*upgrade tablet from android 4.4.2 to 5.1.1. (Phone worked with android 5.0 before)
*I think  android phonegap developper app has been updated

Can you download the app archive locally?
Yes

Can you download the app archive on your mobile device browser? 
No

Can you download the app archive with the PhoneGap mobile app? 
No

Tell us a little more about your app
www folder: 2.14 MB, 153 files 

Does a Hello World App work?
No, but I had it working before without any issue.

Additional info:
I tried to install it on another windows 7 computer, to no avail.

**Comment by Jerkiller** [comment]
1. What operating system are you using?
Windows 10 64-bit.

2. Do you have a software firewall enabled?
Windows Firewall, I also deactivated it having the same issue.

3. Are you using the PhoneGap CLI or PhoneGap Desktop?
PhoneGap Desktop.

4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?
v0.1.11 but I've tried many versions during the last week.

5. What mobile device platform are you using?
Android 5.0.2.

6. In the past, have you successfully paired the CLI/Desktop to the mobile app?
Yes, long time ago, then I unistalled and reinstalled PhoneGap app and desktop and everything went bad.

7. Can you download the app archive locally?
* From the desktop browser I CAN see the project at  x.x.x.x:3000
* From the desktop browser I CANNOT download the zip at to x.x.x.x:3000/__api__/appzip (long wait and then connection refused)
* 192.168.0.x:3000/__api__/appzip I CAN perfectly download the zip (using my internal IP).

8. Can you download the app archive on your mobile device browser?
I use the native Android browser:
* From the desktop browser I CANNOT see the project at  x.x.x.x:3000 (long wait and error)
* 192.168.0.x:3000/__api__/appzip I CAN perfectly download the zip.

9. Can you download the app archive with the PhoneGap mobile app?
Using 192.168.0.x:3000, I CAN perfectly download, extract and run the app.
I CANNOT connect to x.x.x.x:3000, nothing is logged.

10. Tell us a little more about your app
I used a helloworld app.

11. Does a Hello World App work?
The same as above.

**Comment by ppetree** [comment]
1. What operating system are you using?
Vista SP2

2. Do you have a software firewall enabled?
Windows default, port 3000 allowed in app.

3. Are you using the PhoneGap CLI or PhoneGap Desktop?
Desktop

4. What version of the PhoneGap CLI or PhoneGap Desktop are you using?
Desktop: 0.1.11
Developer: latest in the Apple App Store as of: 11/14/2015

5. What mobile device platform are you using?
ipad MC989LL/A WITH IOS 9.1
iphone mc924LL/A WITH IOS 9.1

6. In the past, have you successfully paired the CLI/Desktop to the mobile app?
Succesfully paired in the past but it was via USB


7. Can you download the app archive locally?
Yes and no, I can download it but it can't open: the zip file is invalid: 22 bytes in size.

8. Can you download the app archive on your mobile device browser?
at: http://10.0.0.x:3000 I get the app icon and waiting on deviceready message
at: http://10.0.0.x:3000/_api_/appzip I get an error: Cannot GET /_api_/appzip
at: http://10.0.0.x:3000/__api__/appzip I get an error: download failed. Safari cannot download this file

404 /_api_/appzip  // this is from the ipad safari browser
200 /__api__/appzip  // this is the second attempt

9. Can you download the app archive with the PhoneGap mobile app?
// this came from the phone
200 /__api__/appzip
200 /socket.io/?EIO=2&transport=polling&t=1447530652582-2
200 /socket.io/?EIO=2&transport=polling&t=1447530653194-3&sid=4WlItXkjbf8z17U_AAAA
200 /__api__/autoreload
200 /__api__/autoreload

10. Tell us a little more about your app
On disk: 1.43 mb with 53 total files
App size: who knows.  I see no build file on my laptop.

11. Does a Hello World App work?
Work? don't you think you should define work?
Does the desktop app transmit? yes. It seems to transmit to the browser.
Does the mobile app receive? no. It doesn't appear to.
Now, has this app "worked" in previous dev enviornments and on android devices? yes.
Can I download this app via phonegap build and have it load and run on my android device? yes

**Comment by code-smith** [comment]
What operating system are you using?
OSx 10.10.5

Do you have a software firewall enabled?
No

Are you using the PhoneGap CLI or PhoneGap Desktop?
PhoneGap CLI

What version of the PhoneGap CLI or PhoneGap Desktop are you using?
PhoneGap CLI 5.3.9

What mobile device platform are you using?
IOS 6

In the past, have you successfully paired the CLI/Desktop to the mobile app?
No

Can you download the app archive locally?
Yes

Can you download the app archive on your mobile device browser? 
Yes

Can you download the app archive with the PhoneGap mobile app
No

Tell us a little more about your app
Its just a hello world app which I’m trying to connect for the first time.

Does a Hello World App work?
No

This is the first time I’m using phone gap developer app and I’m not able to connect it form the APP.
All i get is Downloading….
I’m able to connect to the server  on my mobiles safari and also was able to download the zip file on both my mac and iphone

I’m very certain that the problem lies within the app, so let me give more details about the phone
its an iPhone 3gs which is running iOS 6.1.6

**Comment by jhomme** [comment]
One thing I think to check is to ensure, if you are running windows, that the firewall is allowing the node.js to create the server. My apologies for not being technical. I didn't notice that Windows was asking me if I wanted to allow this to happen. Once I allowed it to occur, I got the app to display the hello world app.

**Comment by ppetree** [comment]
Thanks for that. I had allowed node.js access through the firewall so that wasn't the problem.

In the end I deleted node.js and all the crap that goes with it; deleted the android ask/tools and virtually everything that goes with it; deleted desktop build (what a waste that is) etc. Once that was all done and everything even remotely related was deleted I installed the Intel XDK environment and, while its not perfect it's 1000% better than the kludge everyone else is working with.

**Comment by whrdevries** [comment]
1. What operating system are you using? Windows 10 64-bit
2. Do you have a software firewall enabled? yes, but open for Electron
3. Are you using the PhoneGap CLI or PhoneGap Desktop? PhoneGap Desktop
4. What version of the PhoneGap CLI or PhoneGap Desktop are you using? 0.2.1
5. What mobile device platform are you using? iOS 9.2.1 for both iPhone 6 and iPad Air
6. In the past, have you successfully paired the CLI/Desktop to the mobile app? First time. Doesn't work for iPhone, but works for iPad ('device ready')
7. Can you download the app archive locally? zip file downloaded, project files exist. No 404 or any other error in log.
8. Can you download the app archive on your mobile device browser? iPhone: doesn't download beause the server doesn't respond. iPad: didn't try, because the app work there. No 404 or any other error in log.
9. Can you download the app archive with the PhoneGap mobile app? I get only: downloading... - tap to cancel. This repears until I get an error on the iphone screen: "Alert. Unable to download archive from the server. Please enter valid url to connect to." Nothing in the Phonegap Desktop error log.
10. Tell us a little more about your app. This is the Default Hello World example. I can see the change on the iPad by the way (adding Hello in front of Phonegap).
11. Does a Hello World App work? It does on the iPad, not on the iPhone.
I checked the server address multiple times, including the port number. Everything is on the same wireless network. iPhone and iPad use the same iOS version. The iPhone has more free space than the iPad.

**Comment by 11plustwo** [comment]
I'm on a mac using a virtual machine for windows (VMWare) and my issue was solved when I changed the VM's network settings so the VM appears as a separate device on the network. As in, they don't share a local IP.

**Comment by saagarbethi** [comment]
Hi,
when i am making build using phonegap cli vesrion , my app doesn't connect to my application server. But when i am using phonegap 3.6 version it is working. I have no idea what is the problem. can any one help me please.

**Comment by mwbrooks** [comment]
@11plustwo thanks for the tip! I've added it to the [_PhoneGap Developer App_ Troubleshooting section](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/#phonegap-developer-app-is-unable-to-download-from-the-server)

**Comment by ed42311** [comment]
Connection problem between Desktop app and Ipad/ios.
reinstalled PhoneGap globally
reinstalled Phonegap desktop
reinstalled App on Ipad
switched to Hello World App.

Answers

1. **Operating system:** Windows 10, 64-bit
2. **Software firewall is:** disabled.
3. **PhoneGap:** Desktop
4. **PhoneGap:** Desktop 0.3.1
4. **Mobile device platform** IOS 9.3.1 and hopefully when we get it working Android 5.1?
5. **In the past, have you successfully paired the CLI/Desktop to the mobile app?** No, first time.
6.  **Can you download the app archive locally?**
  *  Browse to `x.x.x.x:3000/__api__/appzip  _done_`
  *  Unzip the archive and ensure that your project files exist.  _done_
  *  They exist.  _appzip.zip_
7. **Check Log:** No 404
8. **Mobile Download of zip file**
  *  Browse to ` x.x.x.x:3000/__api__/appzip  _done_`
  *  Attempts to navigate -  then a timeout, "Safari cannot open page because server stopped responding"
  *  nothing in logs 
9. **Download  with PhoneGap mobile app**
  *  `downloading... - tap to cancel.`
  *  "Alert. Unable to download archive from the server. Please enter valid url to connect to."
  *  nothing in logs.
10. **The project is the Default Hello World example.**  Thought I would get that running first.  :smile:
