### ISSUE TITLE
Push does not work as written in tutorial for Windows

### ISSUE THREAD

**Issue by Lukenickerson** [phonegap/phonegap-app-developer#487]
Following along the instructions on http://docs.phonegap.com/develop/push-notifications/ with the default push example that is included with the Windows Phonegap app gives an error on the first "Sending Your First Push" step. I've found that doing `phonegap push --deviceID [whatever device id] --service gcm --payload '{ "data": { "title": "Hello", "message": "World"} }'` (with the appropriate device id entered) gives this error when using PowerShell:

> SyntaxError: Unexpected token d in JSON at position 2
>    at Object.parse (native)
>    at PushCommand.execute
>    at PushCommand.run 
>    at PhoneGap.push 
>    at CLI.module.exports [as push] 
>    at CLI.module.exports [as argv] 
>    at runPhoneGapCommand 
>    at Object.<anonymous> 
>    at Module._compile (module.js:541:32)
>    at Object.Module._extensions..js (module.js:550:10)

And a similar, but different, error when using the vanilla command prompt:

> SyntaxError: Unexpected token ' in JSON at position 0

System: Windows 10, using Phonegap 6.4.3

*Expected:* Instructions would say that they are incompatible with Windows, or provide alternative command line instructions.

**Comment by racingsolution** [comment]
Try this

phonegap push --deviceID [whatever device id] --service gcm --payload '{ \"data\": { \"title\": \"Hello\", \"message\": \"World\"} }'

**Comment by racingsolution** [comment]
Well that didn't work. Add a backslash before each double quote

**Comment by Lukenickerson** [comment]
Thanks @racingsolution .

Outer single quotes and escaped double-quotes worked in PowerShell:
`phonegap push --deviceID [the long device id] --service gcm --payload '{ \"data\": { \"title\": \"Hello\", \"message\": \"World\"} }'`

...whereas outer double-quotes was necessary in the Windows command prompt:
`phonegap push --deviceID [the long device id] --service gcm --payload "{ \"data\": { \"title\": \"Hello\", \"message\": \"World\"} }"`

I would recommend that these instructions be included in the docs.phonegap.com documentation.

**Comment by macdonst** [comment]
@Lukenickerson thanks for pointing this out. I will update the docs. I've added Windows command line instructions in my push workshops but I forgot to update docs.phonegap.com.

**Comment by LordV8or** [comment]
I have tried to run this on Windows to test on my phone (Galaxy S7) and in Chrome. When I use my phone device id it returns back with body: OK, but I do not get a message. When I put in my browser device id, the terminal freezes. Is there anything else I should be doing?
